# Random Forest

**Author:** Saksham Chauhan \
**Year:** 2026

**Education**
- B.Sc. (Hons.) Statistics, University of Delhi
- M.Sc. Statistics, University of Delhi
- M.Tech. Artificial Intelligence & Data Science, IIIT Kottayam *(Ongoing)*

**Connect**
- LinkedIn: https://linkedin.com/in/sakshamstats
- GitHub: https://github.com/sakshamchauhan-stats

# 1. Introduction

Random Forest is an ensemble learning algorithm that combines the predictions of multiple Decision Trees built on different subsets of the training data and features. The final prediction is obtained by aggregating the predictions of individual trees.
- Classification: Majority Voting
- Regression: Mean Prediction
In other words, Random Forest is a bagging algorithm with its trees working on different subsets of features.

### Intuition
A single Decision Tree usually has low bias but high variance, making it prone to overfitting. \
Random Forest reduces this variance by training many independent Decision Trees on different bootstrap (sampling with replacement) samples and allowing each tree to consider only a *random subset of features at every split*. 

Since the trees make different errors, averaging their predictions improves generalization.


### Mathematical Idea

Suppose the training dataset contains n observations and p features.

For each tree:

1. Draw a bootstrap sample (sampling with replacement) from the training data.
2. At every split, randomly select m features (m < p).
3. Choose the best split among these selected features.
4. Grow the tree (usually without pruning).

The two sources of randomness are

- Bootstrap sampling
- Random feature selection

These reduce correlation among trees and improve ensemble performance.

- Supervised Learning
- Ensemble Learning
- Bagging (Bootstrap Aggregating)
- Non-parametric (No fixed functional form is assumed)
- Eager Learner (The model is fully built during training)
- Deterministic 
- Discriminative
- Non-linear
- Batch Learner

### When Random Forest Performs Well

- Non-linear relationships
- Large datasets
- Mixed numerical and categorical data (after encoding)
- High feature interactions
- Moderate noise
- Complex decision boundaries
- Default baseline model for tabular datasets

### When Random Forest Performs Poorly

- Very high-dimensional sparse datasets (e.g. text)
- Extremely small datasets
- Situations requiring high interpretability

# 2. Scikit-Learn Implementation

### Heart Disease Prediction (Classification)
This dataset contains demographic, clinical, and laboratory measurements collected from patients to predict the presence of heart disease. It is a binary classification problem and is widely used for benchmarking supervised classification algorithms.

### Medical Insurance Cost Prediction (Regression)
This dataset contains demographic and lifestyle information such as age, sex, BMI, number of children, smoking status, and region. The objective is to predict an individual's annual medical insurance charges.

#### Classification Model

In [14]:
# Importing libraries
import kagglehub
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [2]:
# Download the latest version of the dataset from Kaggle
path = kagglehub.dataset_download("nalisha/heart-disease-prediction-dataset")

# Load the dataset
df = pd.read_csv(f"{path}/Heart_Disease_Prediction.csv")

# Separate predictors and target
X = df.drop(columns="Heart Disease")
y = df["Heart Disease"]

df.head()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence

In [3]:
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42,
)

In [4]:
# Define model hyperparameters
params = {
    "n_estimators": 200,
    "criterion": "gini",
    "max_depth": 10,
    "min_samples_split": 2,
    "min_samples_leaf": 1,
    "max_features": "sqrt",
    "random_state": 42,
    "n_jobs": -1,
}

# Train the Random Forest classifier
classifier = RandomForestClassifier(**params)
classifier.fit(X_train, y_train)
# Make predictions
y_pred = classifier.predict(X_test)

# Display hyperparameters
print("Hyperparameters\n")
print(classifier.get_params())

# Display important learned attributes
print("\nClasses")
print(classifier.classes_)
print("\nNumber of Classes")
print(classifier.n_classes_)
print("\nNumber of Input Features")
print(classifier.n_features_in_)
print("\nFeature Names")
print(classifier.feature_names_in_)
print("\nNumber of Outputs")
print(classifier.n_outputs_)
print("\nNumber of Trees")
print(len(classifier.estimators_))

Hyperparameters

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 200, 'n_jobs': -1, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}

Classes
['Absence' 'Presence']

Number of Classes
2

Number of Input Features
13

Feature Names
['Age' 'Sex' 'Chest pain type' 'BP' 'Cholesterol' 'FBS over 120'
 'EKG results' 'Max HR' 'Exercise angina' 'ST depression' 'Slope of ST'
 'Number of vessels fluro' 'Thallium']

Number of Outputs
1

Number of Trees
200

In [5]:
# Classification Report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

     Absence       0.86      0.83      0.85        30
    Presence       0.80      0.83      0.82        24

    accuracy                           0.83        54
   macro avg       0.83      0.83      0.83        54
weighted avg       0.83      0.83      0.83        54

In [6]:
# Display feature importances
feature_importance = (
    pd.DataFrame(
        {
            "Feature": X_train.columns,
            "Importance": classifier.feature_importances_,
        }
    )
    .sort_values("Importance", ascending=False)
    .reset_index(drop=True)
)

feature_importance

                    Feature  Importance
0           Chest pain type    0.123281
1                    Max HR    0.116434
2                  Thallium    0.115675
3   Number of vessels fluro    0.114975
4             ST depression    0.103531
5               Cholesterol    0.088495
6                       Age    0.080886
7                        BP    0.075817
8           Exercise angina    0.056150
9               Slope of ST    0.055858
10                      Sex    0.042369
11              EKG results    0.017626
12             FBS over 120    0.008903

#### Regression Model

In [7]:
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_absolute_error,
    root_mean_squared_error,
)

# Download the latest version of the dataset
path = kagglehub.dataset_download("mirichoi0218/insurance")

# Load the dataset
df = pd.read_csv(f"{path}/insurance.csv")

# Separate features and target
X = df.drop(columns="charges")
y = df["charges"]

df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [8]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
)

# Identify numerical and categorical columns
num_cols = X_train.select_dtypes(include=["number"]).columns
cat_cols = X_train.select_dtypes(exclude=["number"]).columns

# One-Hot Encode categorical variables
X_train = pd.get_dummies(X_train, drop_first=True)
X_test = pd.get_dummies(X_test, drop_first=True)

In [9]:
# Define model hyperparameters
params = {
    "n_estimators": 200,
    "criterion": "squared_error",
    "max_depth": 10,
    "min_samples_split": 2,
    "min_samples_leaf": 1,
    "max_features": 1.0,
    "random_state": 42,
    "n_jobs": -1,
}

# Train the Random Forest regressor
regressor = RandomForestRegressor(**params)
regressor.fit(X_train, y_train)
# Make predictions
y_pred = regressor.predict(X_test)


# Display hyperparameters
print("Hyperparameters\n")
print(regressor.get_params())

# Display model attributes
print("\nNumber of Input Features")
print(regressor.n_features_in_)
print("\nFeature Names")
print(regressor.feature_names_in_)
print("\nNumber of Outputs")
print(regressor.n_outputs_)
print("\nNumber of Trees")
print(len(regressor.estimators_))

Hyperparameters

{'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': 10, 'max_features': 1.0, 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 200, 'n_jobs': -1, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}

Number of Input Features
8

Feature Names
['age' 'bmi' 'children' 'sex_male' 'smoker_yes' 'region_northwest'
 'region_southeast' 'region_southwest']

Number of Outputs
1

Number of Trees
200

In [10]:
regressor.estimator_

DecisionTreeRegressor()

In [11]:
# List of all estimators used
regressor.estimators_

[DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1608637542),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1273642419),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1935803228),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=787846414),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=996406378),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1201263687),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=423734972),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=415968276),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=670094950),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1914837113),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=669991378),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=429389014),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=249467210),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1972458954),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1572714583),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1433267572),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=434285667),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=613608295),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=893664919),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=648061058),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=88409749),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=242285876),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=2018247425),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=953477463),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1427830251),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1883569565),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=911989541),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=3344769),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=780932287),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=2114032571),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=787716372),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=504579232),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1306710475),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=479546681),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=106328085),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=30349564),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1855189739),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=99052376),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1250819632),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=106406362),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=480404538),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1717389822),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=599121577),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=200427519),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1254751707),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=2034764475),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1573512143),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=999745294),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1958805693),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=389151677),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1224821422),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=508464061),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=857592370),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1642661739),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=61136438),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=2075460851),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=396917567),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=2004731384),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=199502978),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1545932260),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=461901618),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=774414982),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=732395540),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1934879560),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=279394470),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=56972561),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1927948675),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1899242072),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1999874363),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=271820813),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1324556529),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1655351289),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1308306184),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=68574553),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=419498548),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=991681409),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=791274835),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1035196507),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1890440558),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=787110843),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=524150214),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=472432043),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=2126768636),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1431061255),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=147697582),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=744595490),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1758017741),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1679592528),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1111451555),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=782698033),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=698027879),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1096768899),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1338788865),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1826030589),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=86191493),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=893102645),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=200619113),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=290770691),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=793943861),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=134489564),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=2016850622),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1470101905),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1181686489),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1931679275),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1887633569),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1697157321),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1695770557),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1832485859),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=420477197),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=976125790),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1811936047),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1402481934),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=380072391),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=302554573),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=841739990),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=89482491),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=194249720),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1980718781),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1397283111),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1479761620),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1669356239),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1062231788),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1165435217),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=170476398),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1411916852),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=372593431),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1532243865),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1998256344),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1206604539),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=459708603),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=183378299),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1185407468),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=605264936),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1272485020),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1297926158),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=709816108),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=320192576),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=67157848),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=2091163462),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1818495496),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1169282391),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1696003200),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=853477355),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1260522119),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=23717335),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=60472382),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1354896522),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=854021618),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=888445520),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=907706759),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=983578274),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1246294434),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1165097248),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=455094650),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=318019332),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1830948329),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1539598566),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=648870905),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=497653800),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1782238235),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1559517318),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1503404232),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=529561415),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1930375947),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1421196193),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=409783328),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=272981039),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1592652278),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1335658902),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=725167677),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1396651735),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=712631076),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=986151010),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=392121003),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=590804839),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1179921109),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1663066074),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=263038498),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=2028147648),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1644658402),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=513653348),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=2025988014),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=915879373),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1498573442),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1120063232),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=952321028),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=263183577),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1013547510),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1163795198),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1099805069),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=2120835942),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=173660954),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=97636744),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=904790222),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1836274702),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=476272473),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=109174313),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=1886935931),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=463390156),
 DecisionTreeRegressor(max_depth=10, max_features=1.0, random_state=866377394)]

In [12]:
print("MAE  :", mean_absolute_error(y_test, y_pred))
print("RMSE :", root_mean_squared_error(y_test, y_pred))

MAE  : 2519.1651941957934
RMSE : 4549.106317865641

In [13]:
# Display feature importances
feature_importance = (
    pd.DataFrame(
        {
            "Feature": X_train.columns,
            "Importance": regressor.feature_importances_,
        }
    )
    .sort_values("Importance", ascending=False)
    .reset_index(drop=True)
)

feature_importance

            Feature  Importance
0        smoker_yes    0.618881
1               bmi    0.211287
2               age    0.132916
3          children    0.018072
4          sex_male    0.005547
5  region_northwest    0.004967
6  region_southeast    0.004706
7  region_southwest    0.003624

# 3. Attributes and Hyperparameters

The following hyperparameters control how the forest is constructed, how each Decision Tree grows, how data is sampled, and how the model is trained.

#### n_estimators
Default: 100 \
Admissible Values: int > 0 \
Number of Decision Trees in the forest.
- Too few trees may underfit due to unstable averaging.
- Increasing trees rarely causes overfitting. Performance usually plateaus after a certain point.

#### criterion

Classification Default: gini \
Regression Default: squared_error \
Admissible Values: \
Classification
- "gini"
- "entropy"
- "log_loss" 

Regression
- "squared_error"
- "absolute_error"
- "friedman_mse"
- "poisson"

Criterion used to measure split quality.
- Gini is computationally faster.
- Entropy often produces similar trees but requires more computation.
- Log Loss directly optimizes probabilistic purity.
- Squared Error minimizes variance.
- Absolute Error minimizes absolute deviation but trains more slowly.

#### max_depth
Default: None \
Admissible Values: int > 0, None \
Maximum depth of every tree. 
- Very small values may underfit.
- Unlimited depth may overfit individual trees, although Random Forest reduces this through averaging.

#### min_samples_split
Default: 2 \
Admissible Values: int ≥ 2 \
Minimum number of samples required before splitting a node.
- Higher values lead to simpler trees, lower variance, higher bias.
- Lower values lead to more splits, larger trees, higher variance.


#### min_samples_leaf
Default: 1 \
Admissible Values: int >=1 \
Minimum number of observations allowed in each leaf.
- Higher values result in smoother decision boundaries, may underfit.
- Lower values result in complex trees, overfitting.

#### min_weight_fraction_leaf
Default: 0 \
Admissible Values: float between 0 and 0.5 \
Minimum weighted fraction of total sample weight required at a leaf.

#### max_features
Classification Default: "sqrt" \
Regression Default: 1.0 (all features) \
Admissible Values: int, float, sqrt, log2, None \
Number of features randomly considered at each split.

Smaller values

- Greater diversity.
- Lower correlation between trees.
- Higher bias.

Larger values

- Stronger individual trees.
- Higher correlation.
- Lower bias.
- Higher variance.

#### max_leaf_nodes
Default: None \
Admissible Values: int >1, None \
Maximum number of leaf nodes. \
Restricts tree size. \
Useful when tree complexity must be controlled.

#### min_impurity_decrease
Default: 0 \
Admissible Values: float ≥ 0 \
A split is performed only if impurity decreases by at least this amount. \
Higher values lead to fewer split, smaller trees and better regularisation.

#### bootstrap
Default: True \
Admissible Values: True/False \
Whether bootstrap sampling is performed. \
True

- Standard Random Forest.
- Trees become less correlated.

False

- Every tree receives the complete dataset.
- Trees become more similar.

#### oob_score
Default: False \
Admissible Values: True/False \
Uses Out-of-Bag samples to estimate generalization performance. \
Provides an internal validation score without requiring a validation set.


#### max_samples
Default: None \
Admissible Values: int, float, None \
Number of samples drawn for each bootstrap sample. It fundamentally controls the size of the bootstrap sample used during the bagging process.
- Smaller values: Faster training, greater diversity
- Larger values: Stronger trees, less diversity.

Note: max_samples = None doesn't mean the tree gets the entire data. It is SRSWR and even though the number of samples is equal to the total number of rows in the dataset, some samples can be duplicated.


#### random_state
Default: None \
Admissible Values: int, None, RandomState \
Controls reproducibility.

#### verbose
Default: 0 \
Admissible Values: int>0 \
Controls printed training messages. Useful only for monitoring long training jobs.

#### warm_start
Default: False \
Admissible Values: True/False \
Allows additional trees to be added without rebuilding the forest. Useful when experimenting with n_estimators.

#### class_weight
Default: None \
Admissible Values: None, balanced, balanced_subsample, dictionary \
Modifies the algorithms loss function \
Assigns different importance to different classes. Improves learning for imbalanced datasets. \
Use balanced or balanced_subsample for class imbalance. No need to use SMOTE then. 

#### ccp_alpha
Default: 0 \
Admissible Values: float >=0 \
Cost Complexity Pruning parameter applied to every tree. \
- Larger values: Smaller trees, lower variance, higher bias

#### n_jobs
Default: None \
Admissible Values: None, int, -1 \
Number of CPU cores used during training. \
Use -1 to utilize all available cores.

#### Important Hyperparameter Interactions

- n_estimators and max_features jointly determine ensemble diversity.
- max_depth, min_samples_split, min_samples_leaf and ccp_alpha together control tree complexity.
- bootstrap and max_samples determine sampling diversity.
- bootstrap should generally be True when oob_score=True.
- class_weight affects split selection in imbalanced datasets.

--- 

## Learned Model Attributes
After fitting, a Random Forest exposes several useful attributes.

| Attribute | Description |
|-----------|-------------|
| estimator_ | Template Decision Tree estimator used to build the forest |
| estimators_ | List of fitted Decision Trees |
| feature_importances_ | Mean impurity-based feature importance |
| classes_ | Target class labels (classification) |
| n_classes_ | Number of classes |
| n_outputs_ | Number of outputs |
| n_features_in_ | Number of input features |
| feature_names_in_ | Feature names (if available) |
| oob_score_ | Out-of-Bag score (when enabled) |
| oob_decision_function_ | Out-of-Bag class probabilities |

# 4. Data Requirements

The following points describe how Random Forest behaves under different data conditions and the preprocessing that may be required.

### Feature Scaling
Not required as Random Forest is built using Decision Trees, which split observations based on feature thresholds rather than distance or magnitude. Therefore, the scale of the features does not affect how splits are selected.

### Outliers
Generally robust \
Decision Trees partition the feature space using thresholds. A few extreme observations rarely influence many splits, making Random Forest much less sensitive to outliers than linear or distance-based algorithms.
- Small number of outliers usually has little effect.
- Large number of outliers can still produce noisy splits.

### Missing Values
Missing values must be handled before training as the scikit-learn implementation of Random Forest does not accept NaN values during fitting or prediction.

### Categorical Features
Categorical variables must be encoded. Decision Trees in scikit-learn can only split numerical features.

### High-Dimensional Data
Can handle moderately high-dimensional datasets. \
Each split considers only a subset of features, reducing overfitting caused by many predictors.
- Naturally ignores many irrelevant variables.
- Performs implicit feature selection.

### Multicollinearity
No assumption of independent predictors. Random Forest is relatively insensitive to correlated features because trees select only a subset of features at each split.
- Feature importance may be divided among correlated variables.
- Importance rankings become less reliable. Removing correlated features is usually unnecessary unless model interpretation is important.

### Class Imbalance (Classification)
Moderately sensitive. Majority classes may dominate tree splits and voting.
- Poor recall for minority classes.
- High accuracy but poor minority class performance.

Recommended Techniques

- class_weight="balanced"
- class_weight="balanced_subsample"
- Random Over Sampling
- Random Under Sampling
- SMOTE
- Stratified train-test split

Recommended Evaluation Metrics: Precision, Recall, F1-Score, ROC-AUC


### Feature Selection
Usually not necessary. Random feature selection at each split naturally reduces the influence of irrelevant variables.
- Handles redundant variables well.
- Performs implicit feature selection.
- Too many noisy features increase computation.
- Irrelevant features may slightly reduce predictive performance.

Recommended Techniques
- Remove constant features.
- Remove duplicate features.

### Dimensionality Reduction
Generally unnecessary. Random Forest already performs implicit feature selection through random feature sampling.

### Noise
Highly robust as individual noisy trees are averaged, reducing overall variance. \
Very noisy datasets still reduce predictive performance.

### Data Distribution / Assumptions
Random Forest makes very few statistical assumptions. \
It naturally models

- Non-linear relationships
- Complex feature interactions
- Mixed distributions

# 5. Optimization / Model Improvement

Random Forest is generally less prone to overfitting than a single Decision Tree due to bagging and feature randomness. However, careful tuning of its hyperparameters can significantly improve predictive performance, computational efficiency, and model generalization.

- Increase the Number of Trees
- Control Tree Depth
- Increase Minimum Samples Required to Split
- Increase Minimum Samples per Leaf
- Tune the Number of Features Considered at Each Split (max_features)
- Bootstrap Sampling
- Tune the Bootstrap Sample Size (max_samples_
- Cost Complexity Pruning (ccp_alpha)
- Handle Class Imbalance (class_weights)
- Feature Selection
- Cross Validation

# 6. Summary

### Advantages

- Handles both classification and regression problems.
- Naturally captures non-linear relationships.
- Robust to outliers and noisy data.
- Does not require feature scaling.
- Performs implicit feature selection.
- Handles high-dimensional data reasonably well.
- Reduces overfitting compared to a single Decision Tree.
- Provides feature importance estimates.
- Makes very few assumptions about the underlying data.

### Limitations

- Less interpretable than a single Decision Tree.
- Requires more memory and computational resources.
- Training becomes slower as the number of trees increases.
- Feature importance may be unreliable when predictors are highly correlated.
- Cannot extrapolate well in regression problems.
- Performance may degrade on extremely sparse datasets.

### When to Use

- Strong baseline for structured tabular datasets.
- Complex non-linear relationships.
- Mixed numerical and categorical features.
- Moderate to large datasets.
- When high predictive performance is preferred over interpretability.

### When Not to Use

- Very small datasets.
- Real-time systems with strict latency requirements.
- Problems requiring highly interpretable models.
- Very high-dimensional sparse datasets such as text classification.
- Regression tasks requiring extrapolation beyond the observed data.